[package]
name = "corrode"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = {version = "0.11.3", features = ["gnome_50"]}
gtk4-layer-shell = "0.8.0"
kdlite = "0.1.1"
smallvec = {version = "1.15.1", default-features = false, features = ["union"]}

[profile.release]
lto = 'fat'
strip = true
opt-level = 3
codegen-units = 1
panic = 'abort'
debug = false
incremental = false
